### PR TITLE
Fix extra bees metallic grain crafting recipes

### PR DESCRIPTION
**Pull request by JVital2013**
Fixes issue #630

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Thanks for your contribution! Have you verified that it works without errors in game? :)

**Comment by JVital2013** [comment]
@NillerMedDild works in my installs - running on a Debain server and 2 macOS clients successfully. After the patch all grains in JEI show their correct recipes

**Comment by NillerMedDild** [comment]
Awesome, thanks again :)

**Comment by Lennart247** [comment]
I would suggest adding the following line to the script: 
recipes.addShapeless(<thermalfoundation:material:768>, [<extrabees:misc:18>,<extrabees:misc:18>,<extrabees:misc:18>,<extrabees:misc:18>]);
fixes the coal grain recipe (if removing this wasnt intended) which didnt work either (at least for me).

**Comment by NillerMedDild** [comment]
I have decided to make the change myself, just in case I forgot to merge with master before release ^^' you will of course get full credit for the work JVital2013.
And thank you Lennart247 for the added contribution!

**Comment by JVital2013** [comment]
One more bit to fix: turns out Nutdew to Seed Oil is also broken. According to several wikis, it's supposed to give 200mb seed oil. I have no idea how long it should take to process, so I guessed.

I'm using this code on my server:
```
#Fix Nutdew to seed oil
mods.forestry.Squeezer.addRecipe(<liquid:seed.oil>*200, [<extrabees:honey_drop:7>], 20);
```

Does anyone know what these timings should be?

**Comment by NillerMedDild** [comment]
I usually use 100 (5 seconds)

**Pull request merged**
