### PR TITLE
Update rftools.cfg

### PR DESCRIPTION
**Pull request by Discomanco**
Make the Power Cell able to compete with other battery blocks, prior to infusing it.
5000 rf/t is rather weak

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Changing this value in Expert mode led to many many issues with existing Powercells, so I'm a bit reluctant to make this change, although I agree 5k RF/t is a bit on the low side of the spectrum.

Also, 50k RF/t seems a bit much for a standard Powercell imo.

**Comment by Discomanco** [comment]
Possibly right that 50k is over the top, didn't give too much thought to the amount, other than looking at Expert that's currently sitting at 250k

**Comment by NillerMedDild** [comment]
Ah fair enough - That one is set excessively high in order to make the Creative one output 1MRF/t.

If you make a world with many Powercells (of all types) placed before the config change, and then make the change and can verify they still work, I'm all up for accepting this PR :)

**Comment by Discomanco** [comment]
Aight, will test out :)

**Comment by Discomanco** [comment]
image
Tested with 50 Advanced Powercells, all linked together and fully infused. This is after the config updated

**Comment by Discomanco** [comment]
Git be confusing at times.

Nuclearcraft.cfg update
Put RF Per EU to a unified value. Infinite RF loop is possible otherwise, due to Mekanism conversion rates.

**Comment by NillerMedDild** [comment]
Thanks!

**Pull request merged**
